services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # MINIO_ROOT_USER: myuser
      # MINIO_ROOT_PASSWORD: mypass
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    restart: unless-stopped
    networks:
      - lakehouse

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    restart: on-failure
    #       /usr/bin/mc alias set dockerminio http://minio:9000 myuser mypass;
    # /usr/bin/mc mb dockerminio/faostat-lakehouse;
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb dockerminio/lakehouse;
      exit 0;
      "
    networks:
      - lakehouse
      
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - lakehouse

  spark-master:
    # image: bitnami/spark:3.5.0
    image: bitnamilegacy/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=yes
      - SPARK_RPC_AUTHENTICATION_SECRET=secret
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/data
    restart: unless-stopped
    networks:
      - lakehouse

  spark-worker:
    # image: bitnami/spark:3.5.0
    image: bitnamilegacy/spark:3.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=yes
      - SPARK_RPC_AUTHENTICATION_SECRET=secret
    depends_on:
      - spark-master
    restart: unless-stopped
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/data
    networks:
      - lakehouse

  spark-worker2:
    image: bitnamilegacy/spark:3.5
    container_name: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=yes
      - SPARK_RPC_AUTHENTICATION_SECRET=secret
    depends_on:
      - spark-master
    restart: unless-stopped
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/data
    networks:
      - lakehouse

  airflow-webserver:
    container_name: airflow-webserver
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:password@postgres/metastore
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./jobs:/opt/spark/jobs
      - ./data:/data
    ports:
      - "8088:8080"
      - "7000:7000" # Expose cho Spark Driver giao tiếp: khi ko dung airflow worker
      - "7001:7001"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8088/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - lakehouse

  # Airflow Scheduler
  airflow-scheduler:
    container_name: airflow-scheduler
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:password@postgres/metastore
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./jobs:/opt/spark/jobs
      - ./data:/data
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - lakehouse

  streamlit:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - lakehouse

networks:
  lakehouse:
    driver: bridge

# Conn Id: spark_default
# Conn Type: Spark
# Host: spark://spark-master (hoặc tên service spark://spark-master:7077)
# Port: 7077
# Extra: {"queue": "root.default", "deploy-mode": "client"} (Thường dùng client mode trong docker network).

